import type { Payment } from "@/types"

type PaymentLocale = "en" | "fr" | "ar"

interface PaymentLabels {
  paymentReceipt: string
  patient: string
  date: string
  type: string
  method: string
  totalAmount: string
  status: string
  description: string
  paidOn: string
  stampAndSignature: string
  generatedBy: string
  types: Record<string, string>
  methods: Record<string, string>
  statuses: Record<string, string>
}

const paymentLocales: Record<PaymentLocale, PaymentLabels> = {
  fr: {
    paymentReceipt: "Reçu de Paiement",
    patient: "Patient",
    date: "Date",
    type: "Type",
    method: "Méthode",
    totalAmount: "Montant total",
    status: "Statut",
    description: "Description",
    paidOn: "Payé le",
    stampAndSignature: "Cachet et signature",
    generatedBy: "Généré par Modern AI Clinic OS",
    types: {
      consultation: "Consultation",
      medication: "Médicament",
      follow_up: "Suivi",
      other: "Autre",
    },
    methods: {
      cash: "Espèces",
      card: "Carte bancaire",
      other: "Autre",
    },
    statuses: {
      pending: "En attente",
      paid: "Payé",
      refunded: "Remboursé",
      cancelled: "Annulé",
    },
  },
  en: {
    paymentReceipt: "Payment Receipt",
    patient: "Patient",
    date: "Date",
    type: "Type",
    method: "Method",
    totalAmount: "Total Amount",
    status: "Status",
    description: "Description",
    paidOn: "Paid on",
    stampAndSignature: "Stamp and signature",
    generatedBy: "Generated by Modern AI Clinic OS",
    types: {
      consultation: "Consultation",
      medication: "Medication",
      follow_up: "Follow-up",
      other: "Other",
    },
    methods: {
      cash: "Cash",
      card: "Credit Card",
      other: "Other",
    },
    statuses: {
      pending: "Pending",
      paid: "Paid",
      refunded: "Refunded",
      cancelled: "Cancelled",
    },
  },
  ar: {
    paymentReceipt: "إيصال الدفع",
    patient: "المريض",
    date: "التاريخ",
    type: "النوع",
    method: "طريقة الدفع",
    totalAmount: "المبلغ الإجمالي",
    status: "الحالة",
    description: "الوصف",
    paidOn: "تاريخ الدفع",
    stampAndSignature: "الختم والتوقيع",
    generatedBy: "تم الإنشاء بواسطة Modern AI Clinic OS",
    types: {
      consultation: "استشارة",
      medication: "دواء",
      follow_up: "متابعة",
      other: "أخرى",
    },
    methods: {
      cash: "نقداً",
      card: "بطاقة بنكية",
      other: "أخرى",
    },
    statuses: {
      pending: "قيد الانتظار",
      paid: "مدفوع",
      refunded: "مسترد",
      cancelled: "ملغى",
    },
  },
}

function getDateLocaleStr(locale: PaymentLocale): string {
  switch (locale) {
    case "ar": return "ar-MA"
    case "en": return "en-US"
    default: return "fr-MA"
  }
}

export function printPaymentReceipt(
  payment: Payment,
  clinicName?: string,
  locale?: string
) {
  const lang = (locale && locale in paymentLocales ? locale : "fr") as PaymentLocale
  const labels = paymentLocales[lang]
  const dateLocaleStr = getDateLocaleStr(lang)
  const isRtl = lang === "ar"
  const fontFamily = isRtl
    ? "'Segoe UI', 'Arabic Typesetting', sans-serif"
    : "'Segoe UI', system-ui, -apple-system, sans-serif"

  const patientName = payment.patient
    ? `${payment.patient.first_name} ${payment.patient.last_name}`
    : "—"
  const date = new Date(payment.created_at).toLocaleDateString(dateLocaleStr, {
    day: "numeric",
    month: "long",
    year: "numeric",
  })
  const paidDate = payment.paid_at
    ? new Date(payment.paid_at).toLocaleDateString(dateLocaleStr, {
        day: "numeric",
        month: "long",
        year: "numeric",
      })
    : "—"

  const typeLabels = labels.types
  const methodLabels = labels.methods
  const statusLabels = labels.statuses

  const html = `<!DOCTYPE html>
<html lang="${lang}"${isRtl ? ' dir="rtl"' : ''}>
<head>
  <meta charset="UTF-8">
  <title>${esc(labels.paymentReceipt)} #${payment.id}</title>
  <style>
    @page { margin: 1.5cm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: ${fontFamily}; color: #1a1a1a; font-size: 13px; line-height: 1.5; direction: ${isRtl ? 'rtl' : 'ltr'}; }
    .header { text-align: center; border-bottom: 2px solid #0d9488; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 20px; color: #0d9488; margin-bottom: 4px; }
    .header p { font-size: 12px; color: #666; }
    .receipt-title { text-align: center; font-size: 16px; font-weight: 700; margin-bottom: 24px; text-transform: uppercase; letter-spacing: 1px; color: #333; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 24px; }
    .info-box { background: #f8fafa; border-radius: 8px; padding: 12px; }
    .info-box .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #888; margin-bottom: 4px; }
    .info-box .value { font-size: 14px; font-weight: 600; }
    .amount-box { text-align: center; background: #f0fdfa; border: 2px solid #0d9488; border-radius: 12px; padding: 20px; margin-bottom: 24px; }
    .amount-box .label { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #666; margin-bottom: 8px; }
    .amount-box .amount { font-size: 32px; font-weight: 800; color: #0d9488; }
    .amount-box .currency { font-size: 16px; font-weight: 600; color: #666; }
    .status { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
    .status-paid { background: #d1fae5; color: #065f46; }
    .status-pending { background: #fef3c7; color: #92400e; }
    .footer { margin-top: 40px; display: flex; justify-content: space-between; align-items: flex-end; }
    .signature { text-align: center; }
    .signature .line { width: 200px; border-top: 1px solid #333; margin-bottom: 4px; }
    .signature p { font-size: 11px; color: #666; }
    .watermark { text-align: center; margin-top: 30px; font-size: 9px; color: #ccc; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${esc(clinicName || "Modern Clinic")}</h1>
    <p>${esc(labels.paymentReceipt)}</p>
  </div>

  <div class="receipt-title">${esc(labels.paymentReceipt)} #${payment.id}</div>

  <div class="info-grid">
    <div class="info-box">
      <div class="label">${esc(labels.patient)}</div>
      <div class="value">${esc(patientName)}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.date)}</div>
      <div class="value">${esc(date)}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.type)}</div>
      <div class="value">${esc(typeLabels[payment.payment_type] || payment.payment_type)}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.method)}</div>
      <div class="value">${esc(methodLabels[payment.payment_method] || payment.payment_method)}</div>
    </div>
  </div>

  <div class="amount-box">
    <div class="label">${esc(labels.totalAmount)}</div>
    <div class="amount">${payment.amount.toFixed(2)} <span class="currency">MAD</span></div>
    <div style="margin-top:8px;">
      <span class="status ${payment.status === 'paid' ? 'status-paid' : 'status-pending'}">
        ${esc(statusLabels[payment.status] || payment.status)}
      </span>
    </div>
  </div>

  ${payment.description ? `<div style="background:#f8fafa;border-radius:8px;padding:12px;margin-bottom:24px;"><div style="font-size:10px;text-transform:uppercase;letter-spacing:0.5px;color:#888;margin-bottom:4px;">${esc(labels.description)}</div><div style="font-size:13px;">${esc(payment.description)}</div></div>` : ""}

  ${payment.paid_at ? `<div style="text-align:center;font-size:12px;color:#666;margin-bottom:24px;">${esc(labels.paidOn)}: ${esc(paidDate)}</div>` : ""}

  <div class="footer">
    <div><p style="font-size:11px;color:#666;">${esc(date)}</p></div>
    <div class="signature">
      <div class="line"></div>
      <p>${esc(labels.stampAndSignature)}</p>
    </div>
  </div>

  <div class="watermark">${esc(labels.generatedBy)}</div>
  <script>window.onafterprint = function() { window.close(); };</script>
</body>
</html>`

  const win = window.open("", "_blank", "width=800,height=600")
  if (win) {
    win.document.write(html)
    win.document.close()
    win.focus()
    win.print()
  } else {
    const blob = new Blob([html], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `receipt-${payment.id}.html`
    a.click()
    URL.revokeObjectURL(url)
  }
}

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}
