type CertificateLocale = "en" | "fr" | "ar"

type CertificateType = "sick_leave" | "fitness" | "medical"

interface CertificateLabels {
  certificateTitle: Record<CertificateType, string>
  patient: string
  dateOfBirth: string
  phone: string
  doctor: string
  specialty: string
  licenseNumber: string
  date: string
  certificateNum: string
  diagnosis: string
  from: string
  to: string
  notes: string
  signature: string
  stamp: string
  generatedBy: string
  bodyPrefix: (doctorName: string, patientName: string) => string
  sickLeaveBody: (startDate: string, endDate: string) => string
  fitnessBody: string
  medicalBody: string
  diagnosisPrefix: string
}

const certificateLocales: Record<CertificateLocale, CertificateLabels> = {
  fr: {
    certificateTitle: {
      sick_leave: "CERTIFICAT DE REPOS",
      fitness: "CERTIFICAT D'APTITUDE",
      medical: "CERTIFICAT MÉDICAL",
    },
    patient: "Patient",
    dateOfBirth: "Date de naissance",
    phone: "Téléphone",
    doctor: "Médecin",
    specialty: "Spécialité",
    licenseNumber: "N° d'ordre",
    date: "Date",
    certificateNum: "Certificat N°",
    diagnosis: "Diagnostic",
    from: "Du",
    to: "Au",
    notes: "Observations",
    signature: "Signature et cachet",
    stamp: "Cachet",
    generatedBy: "Généré par Modern AI Clinic OS",
    bodyPrefix: (doc, patient) =>
      `Je soussigné(e), Dr. ${doc}, certifie que ${patient}`,
    sickLeaveBody: (start, end) =>
      `bénéficie d'un repos médical du ${start} au ${end}.`,
    fitnessBody:
      "est médicalement apte à exercer ses activités professionnelles.",
    medicalBody:
      "a été examiné(e) ce jour et que son état de santé est conforme aux constatations ci-dessous.",
    diagnosisPrefix: "Diagnostic :",
  },
  en: {
    certificateTitle: {
      sick_leave: "SICK LEAVE CERTIFICATE",
      fitness: "FITNESS CERTIFICATE",
      medical: "MEDICAL CERTIFICATE",
    },
    patient: "Patient",
    dateOfBirth: "Date of Birth",
    phone: "Phone",
    doctor: "Doctor",
    specialty: "Specialty",
    licenseNumber: "License No.",
    date: "Date",
    certificateNum: "Certificate #",
    diagnosis: "Diagnosis",
    from: "From",
    to: "To",
    notes: "Notes",
    signature: "Signature & Stamp",
    stamp: "Stamp",
    generatedBy: "Generated by Modern AI Clinic OS",
    bodyPrefix: (doc, patient) =>
      `I, the undersigned Dr. ${doc}, certify that ${patient}`,
    sickLeaveBody: (start, end) =>
      `is granted medical leave from ${start} to ${end}.`,
    fitnessBody: "is medically fit to carry out professional activities.",
    medicalBody:
      "has been examined on this date and the following medical findings are noted.",
    diagnosisPrefix: "Diagnosis:",
  },
  ar: {
    certificateTitle: {
      sick_leave: "شهادة راحة طبية",
      fitness: "شهادة اللياقة الطبية",
      medical: "شهادة طبية",
    },
    patient: "المريض",
    dateOfBirth: "تاريخ الازدياد",
    phone: "الهاتف",
    doctor: "الطبيب",
    specialty: "التخصص",
    licenseNumber: "رقم الترخيص",
    date: "التاريخ",
    certificateNum: "شهادة رقم",
    diagnosis: "التشخيص",
    from: "من",
    to: "إلى",
    notes: "ملاحظات",
    signature: "التوقيع والختم",
    stamp: "الختم",
    generatedBy: "تم الإنشاء بواسطة Modern AI Clinic OS",
    bodyPrefix: (doc, patient) =>
      `أنا الموقع أدناه، الدكتور ${doc}، أشهد أن ${patient}`,
    sickLeaveBody: (start, end) =>
      `يستفيد من راحة طبية من ${start} إلى ${end}.`,
    fitnessBody:
      "لائق طبياً لممارسة أنشطته المهنية.",
    medicalBody:
      "تم فحصه في هذا التاريخ وتم تسجيل الملاحظات الطبية التالية.",
    diagnosisPrefix: "التشخيص:",
  },
}

function getDateLocaleStr(locale: CertificateLocale): string {
  switch (locale) {
    case "ar":
      return "ar-MA"
    case "en":
      return "en-US"
    default:
      return "fr-MA"
  }
}

export function printCertificate(certificate: any, locale?: string) {
  const lang = (locale && locale in certificateLocales
    ? locale
    : "fr") as CertificateLocale
  const labels = certificateLocales[lang]
  const dateLocaleStr = getDateLocaleStr(lang)
  const isRtl = lang === "ar"
  const fontFamily = isRtl
    ? "'Segoe UI', 'Arabic Typesetting', sans-serif"
    : "'Segoe UI', system-ui, -apple-system, sans-serif"

  const patientName = certificate.patient_name ?? "—"
  const doctorName = certificate.doctor_name ?? "—"
  const doctorSpecialty = certificate.doctor_specialty ?? "—"
  const doctorLicense = certificate.doctor_license_number ?? "—"
  const certType: CertificateType =
    certificate.type && certificate.type in labels.certificateTitle
      ? certificate.type
      : "medical"
  const title = labels.certificateTitle[certType]

  const formatDate = (dateStr: string | null | undefined): string => {
    if (!dateStr) return "—"
    try {
      return new Date(dateStr).toLocaleDateString(dateLocaleStr, {
        day: "numeric",
        month: "long",
        year: "numeric",
      })
    } catch {
      return dateStr
    }
  }

  const createdDate = formatDate(certificate.created_at)
  const dob = formatDate(certificate.patient_date_of_birth)
  const startDate = formatDate(certificate.start_date)
  const endDate = formatDate(certificate.end_date)

  const bodyPrefix = labels.bodyPrefix(esc(doctorName), esc(patientName))
  let bodyText = ""
  switch (certType) {
    case "sick_leave":
      bodyText = labels.sickLeaveBody(esc(startDate), esc(endDate))
      break
    case "fitness":
      bodyText = labels.fitnessBody
      break
    case "medical":
    default:
      bodyText = labels.medicalBody
      break
  }

  const diagnosisSection = certificate.diagnosis
    ? `<div class="diagnosis">
        <span class="label">${esc(labels.diagnosisPrefix)}</span>
        <span>${esc(certificate.diagnosis)}</span>
      </div>`
    : ""

  const notesSection = certificate.notes
    ? `<div class="notes">
        <div class="label">${esc(labels.notes)}</div>
        <div>${esc(certificate.notes)}</div>
      </div>`
    : ""

  const leavePeriodSection =
    certType === "sick_leave" && certificate.start_date && certificate.end_date
      ? `<div class="period-grid">
          <div class="period-box">
            <span class="label">${esc(labels.from)}</span>
            <span class="value">${esc(startDate)}</span>
          </div>
          <div class="period-box">
            <span class="label">${esc(labels.to)}</span>
            <span class="value">${esc(endDate)}</span>
          </div>
        </div>`
      : ""

  const thTextAlign = isRtl ? "right" : "left"
  const notesBorderSide = isRtl ? "border-right" : "border-left"

  const html = `<!DOCTYPE html>
<html lang="${lang}"${isRtl ? ' dir="rtl"' : ""}>
<head>
  <meta charset="UTF-8">
  <title>${esc(title)} #${certificate.id}</title>
  <style>
    @page { margin: 1.5cm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: ${fontFamily}; color: #1a1a1a; font-size: 13px; line-height: 1.6; direction: ${isRtl ? "rtl" : "ltr"}; }
    .header { text-align: center; border-bottom: 3px solid #0d9488; padding-bottom: 20px; margin-bottom: 24px; }
    .header .logo { width: 60px; height: 60px; margin: 0 auto 8px; background: linear-gradient(135deg, #0d9488, #0891b2); border-radius: 14px; display: flex; align-items: center; justify-content: center; color: white; font-size: 24px; font-weight: 700; }
    .header h1 { font-size: 22px; color: #0d9488; margin-bottom: 2px; letter-spacing: 0.5px; }
    .header .subtitle { font-size: 11px; color: #888; letter-spacing: 1px; text-transform: uppercase; }
    .header .address { font-size: 11px; color: #666; margin-top: 4px; }
    .cert-title { text-align: center; margin: 20px 0; padding: 12px 0; border-top: 1px solid #e0f2f1; border-bottom: 1px solid #e0f2f1; }
    .cert-title h2 { font-size: 18px; color: #0d9488; text-transform: uppercase; letter-spacing: 2px; }
    .cert-title .cert-num { font-size: 11px; color: #999; margin-top: 2px; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 20px; }
    .info-box { background: #f8fafa; border-radius: 8px; padding: 12px; }
    .info-box .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #888; margin-bottom: 4px; }
    .info-box .value { font-size: 13px; font-weight: 600; }
    .body-text { background: #f8fafa; border-radius: 10px; padding: 20px; margin: 20px 0; font-size: 14px; line-height: 1.8; text-align: ${thTextAlign}; }
    .body-text p { margin-bottom: 8px; }
    .diagnosis { margin: 16px 0; padding: 12px 16px; background: #f0fdfa; border-radius: 8px; border: 1px solid #99f6e4; }
    .diagnosis .label { font-weight: 600; color: #0d9488; margin-${isRtl ? "left" : "right"}: 8px; }
    .period-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 16px 0; }
    .period-box { background: #fffbeb; border-radius: 8px; padding: 10px 14px; text-align: center; }
    .period-box .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #92400e; display: block; margin-bottom: 2px; }
    .period-box .value { font-size: 13px; font-weight: 600; color: #78350f; }
    .notes { ${notesBorderSide}: 3px solid #f59e0b; background: #fffbeb; padding: 10px 14px; border-radius: ${isRtl ? "6px 0 0 6px" : "0 6px 6px 0"}; margin: 16px 0; font-size: 12px; }
    .notes .label { font-weight: 600; margin-bottom: 4px; color: #92400e; }
    .footer { margin-top: 48px; display: flex; justify-content: space-between; align-items: flex-end; }
    .footer-date { font-size: 12px; color: #666; }
    .signature-block { text-align: center; }
    .signature-block .line { width: 200px; border-top: 1px solid #333; margin-bottom: 4px; }
    .signature-block p { font-size: 11px; color: #666; }
    .stamp-placeholder { margin-top: 20px; width: 100px; height: 100px; border: 2px dashed #ccc; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 10px; color: #bbb; text-transform: uppercase; letter-spacing: 1px; }
    .watermark { text-align: center; margin-top: 30px; font-size: 9px; color: #ccc; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">MC</div>
    <h1>Modern Clinic</h1>
    <div class="subtitle">Cabinet Médical</div>
    <div class="address">123 Avenue Mohammed V, Marrakech, Morocco &middot; +212 524 000 000</div>
  </div>

  <div class="cert-title">
    <h2>${esc(title)}</h2>
    <div class="cert-num">${esc(labels.certificateNum)} ${certificate.id}</div>
  </div>

  <div class="info-grid">
    <div class="info-box">
      <div class="label">${esc(labels.patient)}</div>
      <div class="value">${esc(patientName)}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.doctor)}</div>
      <div class="value">Dr. ${esc(doctorName)}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.dateOfBirth)}</div>
      <div class="value">${esc(dob)}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.specialty)}</div>
      <div class="value">${esc(doctorSpecialty)}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.phone)}</div>
      <div class="value">${esc(certificate.patient_phone ?? "—")}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.licenseNumber)}</div>
      <div class="value">${esc(doctorLicense)}</div>
    </div>
  </div>

  <div class="body-text">
    <p>${bodyPrefix} ${bodyText}</p>
    ${diagnosisSection}
    ${leavePeriodSection}
  </div>

  ${notesSection}

  <div class="footer">
    <div>
      <p class="footer-date">${esc(labels.date)}: ${esc(createdDate)}</p>
    </div>
    <div class="signature-block">
      <div class="line"></div>
      <p>Dr. ${esc(doctorName)}</p>
      <p>${esc(labels.signature)}</p>
      <div class="stamp-placeholder">${esc(labels.stamp)}</div>
    </div>
  </div>

  <div class="watermark">${esc(labels.generatedBy)}</div>

  <script>window.onafterprint = function() { window.close(); };</script>
</body>
</html>`

  const win = window.open("", "_blank", "width=800,height=600")
  if (win) {
    win.document.write(html)
    win.document.close()
    win.focus()
    win.print()
  } else {
    const blob = new Blob([html], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `certificate-${certificate.id}.html`
    a.click()
    URL.revokeObjectURL(url)
  }
}

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}
