import type { Prescription } from "@/types"

type PrescriptionLocale = "en" | "fr" | "ar"

interface PrescriptionLabels {
  medicalPrescription: string
  patient: string
  doctor: string
  date: string
  prescriptionNum: string
  medication: string
  dosage: string
  frequency: string
  duration: string
  instructions: string
  notes: string
  signature: string
  noMedications: string
  generatedBy: string
}

const prescriptionLocales: Record<PrescriptionLocale, PrescriptionLabels> = {
  fr: {
    medicalPrescription: "Prescription médicale",
    patient: "Patient",
    doctor: "Médecin",
    date: "Date",
    prescriptionNum: "Prescription #",
    medication: "Médicament",
    dosage: "Dosage",
    frequency: "Fréquence",
    duration: "Durée",
    instructions: "Instructions",
    notes: "Notes",
    signature: "Signature",
    noMedications: "Aucun médicament",
    generatedBy: "Généré par Modern AI Clinic OS",
  },
  en: {
    medicalPrescription: "Medical Prescription",
    patient: "Patient",
    doctor: "Doctor",
    date: "Date",
    prescriptionNum: "Prescription #",
    medication: "Medication",
    dosage: "Dosage",
    frequency: "Frequency",
    duration: "Duration",
    instructions: "Instructions",
    notes: "Notes",
    signature: "Signature",
    noMedications: "No medications",
    generatedBy: "Generated by Modern AI Clinic OS",
  },
  ar: {
    medicalPrescription: "وصفة طبية",
    patient: "المريض",
    doctor: "الطبيب",
    date: "التاريخ",
    prescriptionNum: "وصفة رقم",
    medication: "الدواء",
    dosage: "الجرعة",
    frequency: "التكرار",
    duration: "المدة",
    instructions: "التعليمات",
    notes: "ملاحظات",
    signature: "التوقيع",
    noMedications: "لا توجد أدوية",
    generatedBy: "تم الإنشاء بواسطة Modern AI Clinic OS",
  },
}

function getDateLocaleStr(locale: PrescriptionLocale): string {
  switch (locale) {
    case "ar": return "ar-MA"
    case "en": return "en-US"
    default: return "fr-MA"
  }
}

export function printPrescription(
  prescription: Prescription,
  clinicName?: string,
  locale?: string
) {
  const lang = (locale && locale in prescriptionLocales ? locale : "fr") as PrescriptionLocale
  const labels = prescriptionLocales[lang]
  const dateLocaleStr = getDateLocaleStr(lang)
  const isRtl = lang === "ar"
  const fontFamily = isRtl
    ? "'Segoe UI', 'Arabic Typesetting', sans-serif"
    : "'Segoe UI', system-ui, -apple-system, sans-serif"

  const patientName = prescription.patient
    ? `${prescription.patient.first_name} ${prescription.patient.last_name}`
    : "—"
  const doctorName = prescription.doctor?.name ?? "—"
  const date = new Date(prescription.created_at).toLocaleDateString(dateLocaleStr, {
    day: "numeric",
    month: "long",
    year: "numeric",
  })

  const medicationsRows = (prescription.items ?? [])
    .map(
      (item, i) => `
    <tr>
      <td>${i + 1}</td>
      <td><strong>${esc(item.medication_name)}</strong></td>
      <td>${esc(item.dosage)}</td>
      <td>${esc(item.frequency)}</td>
      <td>${esc(item.duration)}</td>
      <td>${esc(item.instructions ?? "—")}</td>
    </tr>`
    )
    .join("")

  const notesBorderSide = isRtl ? "border-right" : "border-left"
  const notesBorderRadius = isRtl ? "6px 0 0 6px" : "0 6px 6px 0"
  const thTextAlign = isRtl ? "right" : "left"

  const html = `<!DOCTYPE html>
<html lang="${lang}"${isRtl ? ' dir="rtl"' : ''}>
<head>
  <meta charset="UTF-8">
  <title>${esc(labels.medicalPrescription)} #${prescription.id}</title>
  <style>
    @page { margin: 1.5cm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: ${fontFamily}; color: #1a1a1a; font-size: 13px; line-height: 1.5; direction: ${isRtl ? 'rtl' : 'ltr'}; }
    .header { text-align: center; border-bottom: 2px solid #0d9488; padding-bottom: 16px; margin-bottom: 20px; }
    .header h1 { font-size: 20px; color: #0d9488; margin-bottom: 4px; }
    .header p { font-size: 12px; color: #666; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 20px; }
    .info-box { background: #f8fafa; border-radius: 8px; padding: 12px; }
    .info-box .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #888; margin-bottom: 4px; }
    .info-box .value { font-size: 14px; font-weight: 600; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th { background: #f0fdfa; color: #0d9488; text-align: ${thTextAlign}; padding: 8px 10px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #e0f2f1; }
    td { padding: 8px 10px; border-bottom: 1px solid #f0f0f0; font-size: 12px; }
    tr:last-child td { border-bottom: none; }
    .notes { background: #fffbeb; ${notesBorderSide}: 3px solid #f59e0b; padding: 10px 14px; border-radius: ${notesBorderRadius}; margin-bottom: 24px; font-size: 12px; }
    .notes .label { font-weight: 600; margin-bottom: 4px; }
    .footer { margin-top: 40px; display: flex; justify-content: space-between; align-items: flex-end; }
    .signature { text-align: center; }
    .signature .line { width: 200px; border-top: 1px solid #333; margin-bottom: 4px; }
    .signature p { font-size: 11px; color: #666; }
    .watermark { text-align: center; margin-top: 30px; font-size: 9px; color: #ccc; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${esc(clinicName || "Modern Clinic")}</h1>
    <p>${esc(labels.medicalPrescription)}</p>
  </div>

  <div class="info-grid">
    <div class="info-box">
      <div class="label">${esc(labels.patient)}</div>
      <div class="value">${esc(patientName)}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.doctor)}</div>
      <div class="value">Dr. ${esc(doctorName)}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.date)}</div>
      <div class="value">${esc(date)}</div>
    </div>
    <div class="info-box">
      <div class="label">${esc(labels.prescriptionNum)}</div>
      <div class="value">${prescription.id}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>${esc(labels.medication)}</th>
        <th>${esc(labels.dosage)}</th>
        <th>${esc(labels.frequency)}</th>
        <th>${esc(labels.duration)}</th>
        <th>${esc(labels.instructions)}</th>
      </tr>
    </thead>
    <tbody>
      ${medicationsRows || `<tr><td colspan="6" style="text-align:center;color:#999;">${esc(labels.noMedications)}</td></tr>`}
    </tbody>
  </table>

  ${
    prescription.notes
      ? `<div class="notes"><div class="label">${esc(labels.notes)}</div>${esc(prescription.notes)}</div>`
      : ""
  }

  <div class="footer">
    <div>
      <p style="font-size:11px;color:#666;">${esc(date)}</p>
    </div>
    <div class="signature">
      <div class="line"></div>
      <p>Dr. ${esc(doctorName)}</p>
      <p>${esc(labels.signature)}</p>
    </div>
  </div>

  <div class="watermark">${esc(labels.generatedBy)}</div>

  <script>window.onafterprint = function() { window.close(); };</script>
</body>
</html>`

  const win = window.open("", "_blank", "width=800,height=600")
  if (win) {
    win.document.write(html)
    win.document.close()
    win.focus()
    win.print()
  } else {
    const blob = new Blob([html], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `prescription-${prescription.id}.html`
    a.click()
    URL.revokeObjectURL(url)
  }
}

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}
